apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-request
spec:
  replicas: 1  # Production ใช้ 2 replicas (base มีแค่ 1)
  template:
    spec:
      # เพิ่ม init container (base ไม่มี)
      initContainers:
      - name: wait-for-db 
        image: busybox:1.35
        command: 
        - sh  
        - -c
        - | 
          echo "Waiting for database to be ready..."
          until nc -z db 5432; do
            echo "Database is unavailable - sleeping"
            sleep 2
          done 
          echo "Database is ready!"
      
      containers:
      - name: it-request
        # เพิ่ม environment variables (base ไม่มี)
        envFrom:
        - configMapRef:
            name: it-request-config
        - secretRef:
            name: it-request-secret
        
        # เพิ่ม health checks (base ไม่มี)
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        
        # ปรับ resources สำหรับ production (override base)
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        
        # เพิ่ม volume mounts (base ไม่มี)
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
      
      # เพิ่ม volumes (base ไม่มี)
      volumes:
      - name: uploads
        emptyDir: {}