apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
# ⭐ ชี้ไปที่ base (เปลี่ยนจาก bases เป็น resources)
resources:
  - ../../base
  - configmap.yaml
  - secret.yaml
# ⭐ ใช้ patch ปรับแต่ง deployment จาก base
patches:
  - path: deployment-patch.yaml
# Jenkins จะมา update tag นี้
# FIXME: Jenkins builds nginx instead of Node.js app for production-* tags
images:
  - name: tanpiyangkoon/it-request-backend
    newTag: production-23b7012589f-42
