apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
# ⭐ ชี้ไปที่ base (เปลี่ยนจาก bases เป็น resources)
resources:
  - ../../base
  - configmap.yaml
  - secret.yaml
# ⭐ ใช้ patch ปรับแต่ง deployment จาก base
patches:
  - path: deployment-patch.yaml
# Jenkins จะมา update tag นี้
images:
  - name: tanpiyangkoon/it-request
    newTag: production-a047c4d83ef-38
