apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base
images:
  - name: tanpiyangkoon/it-request
    newTag: production-216b9a607a4-28
replicas:
  - name: it-request
    count: 2
