apiVersion: v1
kind: Secret
metadata:
  name: it-request-secret
  namespace: default
type: Opaque
stringData:
  # Database Credentials
  PGUSER: "itadmin"
  PGPASSWORD: "P@ssw0rd@samco"
  DB_USER: "itadmin"
  DB_PASSWORD: "P@ssw0rd@samco"