apiVersion: "v1"
kind: "Service"
metadata:
  name: "it-request"
  namespace: "production"
spec:
  selector:
    app: "it-request"
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
    name: "http"
  type: "ClusterIP"