apiVersion: v1
kind: Service
metadata:
  name: it-request
  namespace: production
spec:
  selector:
    app: it-request  # ปรับตาม label ของ Pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80  # พอร์ตที่ Pod ฟัง
  type: ClusterIP